### ISSUE TITLE
PointsSphere fails with Processing 3.0.1

### ISSUE THREAD

**Issue by jimbok8** [codeanticode/pshader-experiments#2]
PointsSphere fails with Processing 3.0.1

Please could you help me to this fix this I am keen to do something similar.
Thanks.

Jim

**Comment by codeanticode** [comment]
Hi @jimbok8, commit https://github.com/codeanticode/pshader-experiments/commit/30805a85eedc654a15d1a157079a58f9711cc2a1 made PointsSphere compatible with 3.0.1, thanks for your report!
